# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@2.1.2
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: sewunet/my-simplenode:latest 

workflows:
  example-workflow:
    jobs:
      - example-job
      - docker/publish:
            image: sewunet/my-simplenode:latest 